### ISSUE TITLE
LOGIN PAGE - develop API

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#32]

**Comment by ghost** [comment]
If the user has logged out/not logged in this page will take a username and password from the user, hash the password and append the salt to the front of the hashed password, then query the database to check if the credentials match what the user entered. If the user did not logout previously then the page will check to see if the session matches and will keep the user previous user logged in if they match. Otherwise the user will be prompted to enter their username and password. I will comment below the commit id for final version.

**Comment by wesleysmith26** [comment]
uploaded to wesley-account-creation branch commit # 1a08f80
